django/usersite/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
app_name="accounts"

urlpatterns = [
    path('signup/', views.SignUpView.as_view(),name="signup"),
    path('profile/', views.profile_view,name="profile"),
    path('profile/update/', views.ProfileUpdate.as_view(),name="profile_update"),
    path('', views.logout_view,name="logout"),
    # path('login/', views.login_view,name="login"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
]

django/usersite/posts/urls.py
from django.urls import path
from . import views


app_name="posts"

urlpatterns = [

    path('posts/', views.AddPost.as_view(),name="posts"),
    path('posts/likepost/', views.AddLike.as_view(),name="like"),
]

django/usersite/usersite/urls.py
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
	path('',include('accounts.urls')),
	path('',include('posts.urls')),
    path('admin/', admin.site.urls),
]

django/usersite/accounts/models.py
from django.db import models

# Create your models here.

django/usersite/posts/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content=models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
    	return self.title

class Like(models.Model):
	post=models.ForeignKey(Post, on_delete=models.CASCADE)
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	time=models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.post.title

django/usersite/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model=User
		fields= ['username','email','first_name','last_name','password']


class ProfileForm(forms.ModelForm):
	
	class Meta:
		model=User
		fields= ['email','first_name','last_name']

django/usersite/posts/forms.py
from django import forms
from .models import Post


class PostCreationForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=['title','content']

django/usersite/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.views.generic  import View
from django.views.generic.edit  import UpdateView
from django.contrib.auth.decorators import login_required
from .forms import UserForm,ProfileForm
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.models import 
from django.views.generic.edit import FormView
# Create your views here.
class SignUpView(View):
	form_class=UserForm
	template_name="accounts/signup.html"

	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form=self.form_class(request.POST)
		if form.is_valid():
			user=form.save(commit=False)

			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()


			user=authenticate(username=username,password=password)

			if user is not None:

				if user.is_active:
					login(request,user)
					return redirect('accounts:profile')

		return render(request,self.template_name,{'form':form})

@login_required(login_url='accounts:login')
def profile_view(request):
	template_name="accounts/profile.html"
	return render(request,template_name) 

def logout_view(request):
	logout(request)
	return redirect('accounts:login')

class ProfileUpdate(LoginRequiredMixin,FormView):
	login_url='accounts:login'
	form_class =ProfileForm
	template_name="accounts/update.html"
	# success_url = 'accounts:profile'
	def get(self,request):
		form=self.form_class(instance=request.user)
		return render(request,self.template_name,{'form':form},)
	def post(self,request):
		form=self.form_class(request.POST,instance=request.user)
		if form.is_valid():
			form.save()
			return redirect("accounts:profile")		
		

django/usersite/posts/views.py
from django.shortcuts import render,redirect
from django.views import View
from .models import Post,Like
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostCreationForm
from django.utils import timezone
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods


class AddPost(LoginRequiredMixin,View):
	login_url='accounts:login'
	form_class =PostCreationForm
	template_name="posts/posts.html"
	def get(self,request):
		post_list = Post.objects.values().order_by('-pub_date')		
		for post in post_list:
			post['author']=Post.objects.get(id=post['id']).author
			post['likecount']=Like.objects.filter(post=post['id']).count()
			likeduser=Like.objects.filter(post=post['id'],user=request.user)
			if likeduser.exists():
				post['do']="Unlike"
			else:
				post['do']="Like"
		form=self.form_class(instance=request.user)
		context={'form':form,'post_list':post_list ,}		
		return render(request,self.template_name,context)
	def post(self,request):
		title_text = request.POST.get('title_input')
		content_text=request.POST.get('content_input')
		response_data = {}
		post = Post(title=title_text,content=content_text, author=request.user)
		post.save()
		response_data['id']=post.id
		response_data['title'] = post.title
		response_data['content'] = post.content
		response_data['pub_date'] = post.pub_date.strftime('%B %d, %Y %I:%M %p')
		response_data['author'] = post.author.username
		
		return JsonResponse(response_data) 

class AddLike(LoginRequiredMixin,View):
	login_url='accounts:login'
	def post(self,request):		
		pid = request.POST.get('postid')
		like=Like(post=Post.objects.get(id=pid),user=request.user)
		print(like.post)
		print(like.user)
		likeduser=Like.objects.filter(post=pid,user=request.user)
		if likeduser.exists():			
			likeduser.delete()
			message = 'Like'
		else:			
			like.save()
			message = 'Unlike'

		total_likes=Like.objects.filter(post=pid).count()
		ctx = {'likes_count': total_likes, 'message': message}
		print(ctx)
		# use mimetype instead of content_type if django < 5
		return JsonResponse(ctx)

django/usersite/accounts/templates/accounts/base.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />

</head>
<body>
<div id="wrapper">
<h1>hi {{user.username}}</h1>
<a href="{% url 'accounts:profile' %}">Home</a>
<a href="{% url 'accounts:logout' %}">Logout</a>
<a href="{% url 'posts:posts' %}">View Posts</a>

{%block contents%}


{%endblock%}
</div>


</body>
</html>

django/usersite/accounts/templates/accounts/login.html
<h1>Login</h1>

<form method="post" action="{% url 'accounts:login' %}">
	{% csrf_token %}
	<table>
		<tr>
		    <td>{{ form.username.label_tag }}</td>
		    <td>{{ form.username }}</td>
		</tr>
		<tr>
		    <td>{{ form.password.label_tag }}</td>
		    <td>{{ form.password }}</td>
		</tr>
	</table>
	{% if form.errors %}
		<p>Your username and password didn't match. Please try again.</p>
	{% endif %}
	<input type="submit" value="login" />
	<input type="hidden" name="next" value="{% url 'accounts:profile'%}" />
</form>

django/usersite/accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{%block contents%}
<br>
<br>
<h1>Profile Details</h1>
<h4>Email: {{user.email}}</h4>
<h4>Firstname: {{user.first_name}}</h4>
<h4>LastName: {{user.last_name}}</h4>

<!--{# <a href="{% url 'accounts:logout' %}">Logout</a> #}-->
<a href="{% url 'accounts:profile_update' %}">Update Profile</a>
{%endblock%}

django/usersite/accounts/templates/accounts/signup.html
<h1>Signup Form</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Sign up</button>
</form>

<a href="{% url 'accounts:login' %}">Login</a>

django/usersite/accounts/templates/accounts/update.html
{% extends "accounts/base.html" %}

{%block contents%}

<form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

{%endblock%}

django/usersite/posts/templates/posts/posts.html
{% extends "accounts/base.html" %}
{% load static%}
{% block contents%}
<form action="" method="post" id="post-form">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    
</form>

<div id="articles">
{% for post in post_list%}
	<p>Title:{{post.title}}</p>
	<p>Content:{{post.content}}</p>
	<p>Author:{{post.author}}</p>
	<p>written at:{{post.pub_date}}</p>
	<p>Likes:<span id="likecount{{ post.id }}">{{post.likecount}}</span></p>
	<input type="button" class="like" id="post{{ post.id }}"  value="{{post.do}}"/>
	<br>
	<br>
{% endfor%}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'posts/js/main.js' %}" type="text/javascript" charset="utf-8" async defer></script>
{%endblock%}